export const GET_BUSINESS = 'GET_BUSINESS';

export const GET_USERDATA = 'GET_USERS';

export const GET_AVAILABLE_TIME = "GET_AVAILABLE_TIME";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const GET_USER_APPOINTMENT = "GET_USER_APPOINTMENT";
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const GET_BUSINESS_APPOINTMENT = 'GET_BUSINESS_APPOINTMENT';
export const ALLOW_APPOINTMENT = 'ALLOW_APPOINTMENT';
export const CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT';